# -*- coding: utf-8 -*-
"""GRAPHRAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fooLgxVS__VwPZPjkuHVxJKlpLhGRCyl
"""

pip install graphrag

from google.colab import userdata
userdata.get('graphkey')

mkdir input



!python -m graphrag.index --init  --root .

# Commented out IPython magic to ensure Python compatibility.
# %ls

!python -m graphrag.index --root .

!python -m graphrag.query --root . --method local "Whats the main theme of the story?"